apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy           # Base64 für "mongouser"
  mongo-password: bW9uZ29wYXNzd29yZA== # Base64 für "mongopassword"
