apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy  # Base64 von 'mongouser'
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0cHdk  # Base64 von 'secretpwd'
