#cloud-config
# source: https://gist.github.com/syntaqx/9dd3ff11fb3d48b032c84f3e31af9163
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [users, admin]
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUSTV03qWdBRMyVw5cjXCaOpcqkP/aH0TvJ4cfMk65dqkDAoJWiyLzYbB0KDsHjx/M1LEPc8QHmQSVq0jt7pMBvNywqFM069+lcevuaUJs875QoJDsqCmYIHwgFepmI4vYwHsk5/qseijmoTEC2/gp45YmuZI9jJcx5lNWf8ta4d0/u/WEs+HEU+j+TB7Uw9DMMyq1alW7K1D9LDcjBtyPdQ2sZV9QydalmtPvzJXJwRkUP6rtOvLsTO5ft1m/0Cs9QoJzkeMiodR9F4yzCgcSAREZUrsL+VwVVo/MVjNs2bHc/8QGAl2jZxb1/078nOsM6iyjDE1Goz49oTtBXeRz mine_347
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
groups:
  - docker
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
final_message: "The system is finally up, after $UPTIME seconds"
write_files:
  - path: /home/ubuntu/docker-compose.yml
    permissions: '0644'
    content: |
      version: '3'
      services:
        db:
          container_name: m347-kn04a-db
          image: mariadb:latest
          environment:
            MYSQL_ROOT_PASSWORD: root
          networks:
            kn04a-network:
              ipv4_address: 172.20.5.11
        web:
          container_name: m347-kn04a-web
          build:
            context: .
            dockerfile: apache/dockerfile
          networks:
            kn04a-network:
              ipv4_address: 172.20.5.10
          ports:
            - "80:80"
          depends_on:
            - db
      networks:
        kn04a-network:
          driver: bridge
          ipam:
            driver: default
            config:
              - subnet: 172.20.0.0/16
                ip_range: 172.20.5.0/24
                gateway: 172.20.5.254
  - path: /home/ubuntu/apache/db.php
    permissions: '0644'
    content: |
      <?php
      $servername = "m347-kn04a-db";
      $username = "root";
      $password = "root";
      $dbname = "mysql";

      $conn = new mysqli($servername, $username, $password, $dbname);
      if ($conn->connect_error) {
          die("Connection failed: " . $conn->connect_error);
      }

      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while ($row = $result->fetch_assoc()) {
          echo ("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
      }
  - path: /home/ubuntu/apache/info.php
    permissions: '0644'
    content: |
      <?php
      phpinfo();
  - path: /home/ubuntu/apache/dockerfile
    permissions: '0644'
    content: |
      FROM php:8.0-apache
      WORKDIR /var/www/html
      RUN docker-php-ext-install mysqli
      EXPOSE 80
      COPY apache/ .
runcmd:
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu
  - chmod 777 /var/run/docker.sock
  - chown -R ubuntu:ubuntu /home/ubuntu
  - cd /home/ubuntu
  - docker compose up -d
