# official dockerimage from nginx, all configurations and functions included 
FROM nginx 
# change the working directory to /usr/share/nginx/html
WORKDIR /usr/share/nginx/html 
# copy the file helloworld.html to the current working directory
COPY helloworld.html .
# expose port 80 to the outside world
EXPOSE 80
