version: "3.8"

services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    volumes:
      - type: volume
        source: mydata
        target: /data
      - type: bind
        source: ./binddata
        target: /bind
      - type: tmpfs
        target: /tmpfs
  nginx2:
    image: nginx:latest
    container_name: nginx2
    volumes:
      - mydata:/data

volumes:
  mydata: