
services:
  db:
    image: mariadb:latest
    container_name: m347-kn04a-db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mysql
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=root
    networks:
      m347_net:
        ipv4_address: 172.10.5.10

  web:
    build:
      context: .
      dockerfile: dockerfile
    image: r00n35/m347-kn04a-web
    container_name: m347-kn04a-web
    ports:
      - "80:80"
    networks:
      m347_net:
        ipv4_address: 172.10.5.11

networks:
  m347_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          ip_range: 172.10.5.0/24
          gateway: 172.10.5.254
